name: Generate Pacman Contribution Graph

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: VishalSingh-07/pacman-contribution-graph@main
        with:
          github_user_name: BappiGorain

      - name: Deploy files
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
