name: Generate Pacman Contribution Graph

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman
        uses: Platane/snk@v3
        with:
          github_user_name: BappiGorain
          outputs: |
            dist/pacman-contribution-graph-dark.svg?palette=github-dark&animation=pacman

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
